# SPDX-License-Identifier: GPL-2.0-only

stages:
    - check

.pacman_install:
    before_script:
        # NOTE: Install latest archlinux-keyring before upgrading system. In the
        # future this should not be needed anymore when we can guarantee a valid
        # keyring for longer:
        # https://gitlab.archlinux.org/archlinux/archlinux-keyring/-/issues/4
        - echo -e "\e[0Ksection_start:`date +%s`:pacman[collapsed=true]\r\e[0KInstalling dependencies"
        - pacman -Sy --needed --noconfirm archlinux-keyring
        - pacman --noconfirm -Syu --needed bats bats-assert bats-support diffutils git jq kcov lzop meson pkg-config shellcheck systemd-ukify
        - echo -e "\e[0Ksection_end:`date +%s`:pacman\r\e[0K"
        - echo -e "\e[0Ksection_start:`date +%s`:useradd[collapsed=true]\r\e[0KCreating non-root user..."
        - useradd -d /builds/${GITLAB_USER_LOGIN} -M builder
        - chown -R builder:builder ..
        - echo -e "\e[0Ksection_end:`date +%s`:useradd\r\e[0K"

shellcheck:
    stage: check
    extends: .pacman_install
    script:
        - sudo -HEu builder meson setup build -Ddocs=false
        - sudo -HEu builder meson test -C build --suite shellcheck
    tags:
        - vm

test:
    stage: check
    extends: .pacman_install
    script:
        - sudo -HEu builder meson setup build -Ddocs=false
        - sudo -HEu builder meson test -C build --suite bats
    artifacts:
        reports:
            junit: build/meson-logs/testlog.junit.xml
    tags:
        - vm

coverage:
    stage: check
    extends: .pacman_install
    coverage: '/Percent covered\s+\d+\.\d+/'
    allow_failure: true
    script:
        - sudo -HEu builder meson setup build -Ddocs=false
        - sudo -HEu builder meson test -C build --suite coverage
        - jq -r '. |
            ["Percent covered", .percent_covered],
            ["Covered lines", .covered_lines],
            ["Total lines", .total_lines],
            ["Percent low", .percent_low],
            ["Percent high", .percent_high] | @tsv' build/coverage/kcov-merged/coverage.json
    artifacts:
        reports:
            coverage_report:
                coverage_format: cobertura
                path: build/coverage/kcov-merged/cobertura.xml
    tags:
        - vm
